List locations = [
  {"name": "Amman", "id": 1},
  {"name": 'Irbid', "id": 2},
  {"name": 'Zarqa', "id": 3},
];

List categories = [
  {'id': 1, 'name': 'Espresso'},
  {'id': 2, 'name': 'Cappuccino'},
  {'id': 3, 'name': 'Latte'},
  {'id': 4, 'name': 'Mocha'},
  {'id': 5, 'name': 'Cold Brew'},
  {'id': 6, 'name': 'Tea'},
];
List products = [
  {
    "id": 1,
    "name": "Espresso",
    "price": 10,
    "category": 1,
    "image": "assets/images/espresso.jpg",
  },
  {
    "id": 2,
    "name": "Double Espresso",
    "price": 12,
    "category": 1,
    "image": "assets/images/espresso.jpg",
  },
  {
    "id": 3,
    "name": "Espresso Macchiato",
    "price": 14,
    "category": 1,
    "image": "assets/images/espresso.jpg",
  },
  {
    "id": 4,
    "name": "Espresso Con Panna",
    "price": 15,
    "category": 1,
    "image": "assets/images/espresso.jpg",
  },
  {
    "id": 5,
    "name": "Cappuccino",
    "price": 15,
    "category": 2,
    "image": "assets/images/cappuccino.jpg",
  },
  {
    "id": 6,
    "name": "Iced Cappuccino",
    "price": 18,
    "category": 2,
    "image": "assets/images/cappuccino.jpg",
  },
  {
    "id": 7,
    "name": "Dry Cappuccino",
    "price": 16,
    "category": 2,
    "image": "assets/images/cappuccino.jpg",
  },
  {
    "id": 8,
    "name": "Flavored Cappuccino (Vanilla)",
    "price": 17,
    "category": 2,
    "image": "assets/images/cappuccino.jpg",
  },
  {
    "id": 9,
    "name": "Flavored Cappuccino (Caramel)",
    "price": 17,
    "category": 2,
    "image": "assets/images/cappuccino.jpg",
  },
  {
    "id": 10,
    "name": "Latte",
    "price": 20,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 11,
    "name": "Iced Latte",
    "price": 22,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 12,
    "name": "Vanilla Latte",
    "price": 23,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 13,
    "name": "Caramel Latte",
    "price": 23,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 14,
    "name": "Hazelnut Latte",
    "price": 23,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 15,
    "name": "Mocha",
    "price": 25,
    "category": 4,
    "image": "assets/images/mocha.jpg",
  },
  {
    "id": 16,
    "name": "Iced Mocha",
    "price": 28,
    "category": 4,
    "image": "assets/images/mocha.jpg",
  },
  {
    "id": 17,
    "name": "White Chocolate Mocha",
    "price": 27,
    "category": 4,
    "image": "assets/images/mocha.jpg",
  },
  {
    "id": 18,
    "name": "Peppermint Mocha",
    "price": 29,
    "category": 4,
    "image": "assets/images/mocha.jpg",
  },
  {
    "id": 19,
    "name": "Cold Brew",
    "price": 30,
    "category": 5,
    "image": "assets/images/cold-brew.jpg",
  },
  {
    "id": 20,
    "name": "Nitro Cold Brew",
    "price": 32,
    "category": 5,
    "image": "assets/images/cold-brew.jpg",
  },
  {
    "id": 21,
    "name": "Cold Brew with Sweet Cream",
    "price": 34,
    "category": 5,
    "image": "assets/images/cold-brew.jpg",
  },
  {
    "id": 22,
    "name": "Flavored Cold Brew (Vanilla)",
    "price": 33,
    "category": 5,
    "image": "assets/images/cold-brew.jpg",
  },
  {
    "id": 23,
    "name": "Black Tea",
    "price": 12,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
  {
    "id": 24,
    "name": "Green Tea",
    "price": 12,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
  {
    "id": 25,
    "name": "Herbal Tea (Chamomile)",
    "price": 14,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
  {
    "id": 26,
    "name": "Iced Tea",
    "price": 15,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
  {
    "id": 27,
    "name": "Chai Latte",
    "price": 24,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
  {
    "id": 34,
    "name": "Americano",
    "price": 14,
    "category": 1,
    "image": "assets/images/espresso.jpg",
  },
  {
    "id": 35,
    "name": "Iced Americano",
    "price": 16,
    "category": 1,
    "image": "assets/images/espresso.jpg",
  },
  {
    "id": 36,
    "name": "Flat White",
    "price": 18,
    "category": 2,
    "image": "assets/images/cappuccino.jpg",
  },
  {
    "id": 37,
    "name": "Spanish Latte",
    "price": 24,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 38,
    "name": "Iced Spanish Latte",
    "price": 26,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 39,
    "name": "Dark Chocolate Mocha",
    "price": 28,
    "category": 4,
    "image": "assets/images/mocha.jpg",
  },
  {
    "id": 40,
    "name": "Salted Caramel Cold Brew",
    "price": 35,
    "category": 5,
    "image": "assets/images/cold-brew.jpg",
  },
  {
    "id": 41,
    "name": "Earl Grey Tea",
    "price": 13,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
  {
    "id": 42,
    "name": "Matcha Latte",
    "price": 25,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
  {
    "id": 45,
    "name": "Ristretto",
    "price": 11,
    "category": 1,
    "image": "assets/images/espresso.jpg",
  },
  {
    "id": 46,
    "name": "Cortado",
    "price": 16,
    "category": 2,
    "image": "assets/images/cappuccino.jpg",
  },
  {
    "id": 47,
    "name": "Pistachio Latte",
    "price": 25,
    "category": 3,
    "image": "assets/images/latte.jpg",
  },
  {
    "id": 48,
    "name": "Raspberry Mocha",
    "price": 29,
    "category": 4,
    "image": "assets/images/mocha.jpg",
  },
  {
    "id": 49,
    "name": "Coconut Cold Brew",
    "price": 34,
    "category": 5,
    "image": "assets/images/cold-brew.jpg",
  },
  {
    "id": 50,
    "name": "Lemon Iced Tea",
    "price": 16,
    "category": 6,
    "image": "assets/images/tea.jpg",
  },
];
